### ISSUE TITLE
error saving and updating token, Lesson 3 - Password Reset Flow

### ISSUE THREAD

**Issue by kaadoshi66** [adocasts/user-role-authentication-example#1]

**Comment by kaadoshi66** [comment]
> Hi, today I was following your tutorial and applying it, when I got to the test this error occurred:
> 
> [13:52:14.060] ERROR (s.o/16588): update `token_oblivions` set `expires_at` = 2023-02-09 13:52:13.996 -03:00 where (`type` = 'PASSWORD_RESET') and (`user_id` = 1) - Unknown column '_zone' in 'field list' err: { "type": "Error", "message": "update `token_oblivions` set `expires_at` = 2023-02-09 13:52:13.996 -03:00 where (`type` = 'PASSWORD_RESET') and (`user_id` = 1) - Unknown column '_zone' in 'field list'", "stack": Error: update `token_oblivions` set `expires_at` = 2023-02-09 13:52:13.996 -03:00 where (`type` = 'PASSWORD_RESET') and (`user_id` = 1) - Unknown column '_zone' in 'field list',
> 
> I cloned your repo, to confirm that I did it wrong, but the error persisted

**Comment by XenriseZPH** [comment]
any solution on this?

**Comment by tomgobich** [comment]
Someone on the Adocasts site stated the below worked for them. 

```ts
public static async expireTokens(user: User) {
  await user.related('passwordResetTokens').query().update({
    expiresAt: DateTime.now().toFormat('yyyy-MM-dd HH:mm:ss')
  })
}
```

You could also try:
```ts
public static async expireTokens(user: User) {
  await user.related('passwordResetTokens').query().update({
    expiresAt: DateTime.now().toSQL({ includeZone: false })
  })
}
```

Seems like the timezone within the datetimes is primarily what's caused issues for some.
https://adocasts.com/series/adonisjs-user-roles/lessons/how-to-create-a-password-reset-flow-in-nodejs-with-adonisjs#comment211
